--- 

- name: Create temp cert manager working directory
  tempfile:
    state: directory
    suffix: certmgr
  register: certmgr_tmp
  notify: Remove certmgr temp dir

- name: Add Jetstack Helm Chart Repo (for Cert-Manager)
  command: >
    helm repo add jetstack {{ cert_manager_helm_chart_repo }}
  register: jetstack_add_repo
  changed_when: '"has been added to your repositories" in jetstack_add_repo.stdout'

- name: Install Cert Manager with CRDs
  command:
    cmd: >
      helm upgrade --install
      cert-manager jetstack/cert-manager
      --namespace cert-manager
      --create-namespace
      --version {{ cert_manager_version }}
      --set installCRDs=true
  environment:
    KUBECONFIG: "{{ k3s_kubeconfig_path }}"
  register: manifest
  changed_when:
    - '"cannot re-use a name that is still in use" not in manifest.stderr'
  failed_when:
    - manifest.rc != 0
    - '"cannot re-use a name that is still in use" not in manifest.stderr'

- name: Create the ExternalSecret manifest file holding Sectigo ACME credentials 
  template: 
    src: "es-sectigo-acme-creds.j2"
    dest: "{{ certmgr_tmp.path }}/es-sectigo-acme-creds.j2"

- name: Create the ExternalSecret resource for Sectigo ACME credentials 
  command: > 
    kubectl apply -f {{ certmgr_tmp.path }}/es-sectigo-acme-creds.j2
  environment:
    KUBECONFIG: "{{ k3s_kubeconfig_path }}"

- name: Copy Sectigo EAB ClusterIssuer file
  copy: 
    src: "sectigo.yaml"
    dest: "{{ certmgr_tmp.path }}/sectigo.yaml"

- name: Deploy ClusterIssuer
  command: > 
    kubectl apply -f {{ certmgr_tmp.path }}/sectigo.yaml
  environment:
    KUBECONFIG: "{{ k3s_kubeconfig_path }}"
