---

- name: Create temp gitops working directory
  tempfile:
    state: directory
    suffix: gitops
  register: gitops_tmp
  notify: Remove gitops temp dir

- name: Pull GitHub Repo with env-specific values file
  git: 
    repo: "{{ argocd_values_file_repo_url }}"
    dest: "{{ gitops_tmp.path }}"
    version: "main"

- name: Install ArgoCD
  command:
    cmd: |
      helm upgrade --install 
        argocd argo/argo-cd
        --namespace argocd 
        -f {{ gitops_tmp.path }}/{{ argocd_env_values_path }}
        --create-namespace
        --version {{ argocd_version }}
  environment:
    KUBECONFIG: "{{ k3s_kubeconfig_path }}"
  register: manifest
  changed_when:
    - '"cannot re-use a name that is still in use" not in manifest.stderr'
  failed_when:
    - manifest.rc != 0
    - '"cannot re-use a name that is still in use" not in manifest.stderr'

