---

- name: Create temp gitops working directory
  tempfile:
    state: directory
    suffix: gitops
  register: gitops_tmp
  notify: Remove gitops temp dir

- name: Create temp working space
  tempfile:
    state: directory
    suffix: argocd_wd
  register: argocd_wd

#- name: Pull GitHub Repo with env-specific values file
#  git: 
#    repo: "{{ argocd_values_file_repo_url }}"
#    dest: "{{ gitops_tmp.path }}"
#    version: "main"
#
- name: Copy argocd-values locally
  copy:
    src: values.yaml
    dest: "{{ argocd_wd.path }}"

- name: Install ArgoCD using env-specific values file
  command:
    cmd: >
      helm upgrade --install 
        argocd argo/argo-cd
        --namespace argocd 
        -f {{ argocd_wd.path }}/values.yaml
        --create-namespace
        --version {{ argocd_version }}
  environment:
    KUBECONFIG: "{{ k3s_kubeconfig_path }}"
  register: manifest
  changed_when:
    - '"cannot re-use a name that is still in use" not in manifest.stderr'
  failed_when:
    - manifest.rc != 0
    - '"cannot re-use a name that is still in use" not in manifest.stderr'
