---

- name: Create temp gitops working directory
  tempfile:
    state: directory
    suffix: gitops
  register: gitops_tmp
  notify: Remove gitops temp dir

- name: Create temp working space
  tempfile:
    state: directory
    suffix: argocd_wd
  register: argocd_wd
  notify: Remove argocd temp dir

- name: Copy argocd-values locally
  git:
    git: "{{ argocd_values_repo_url }}"
    dest: "{{ argocd_wd.path }}"

- name: Install ArgoCD using env-specific values file
  command:
    cmd: >
      helm upgrade --install 
        argocd argo/argo-cd
        --namespace {{ argocd_namespace }}
        -f {{ argocd_wd.path }}/{{ argocd_values_path }}
        --create-namespace
        --version {{ argocd_version }}
  environment:
    KUBECONFIG: "{{ k3s_kubeconfig_path }}"
  register: manifest
  changed_when:
    - '"cannot re-use a name that is still in use" not in manifest.stderr'
  failed_when:
    - manifest.rc != 0
    - '"cannot re-use a name that is still in use" not in manifest.stderr'
