--- 

- name: Install External Secrets
  command:
    cmd: >
      helm upgrade --install
      external-secrets external-secrets/external-secrets
      --namespace external-secrets
      --create-namespace
      --version {{ external_secrets_version }}
  environment:
    KUBECONFIG: "{{ k3s_kubeconfig_path }}"
  register: manifest
  changed_when:
    - '"cannot re-use a name that is still in use" not in manifest.stderr'
  failed_when:
    - manifest.rc != 0
    - '"cannot re-use a name that is still in use" not in manifest.stderr'
