--- 

- name: Create temp external secrets working directory
  tempfile:
    state: directory
    suffix: externsecret
  register: externsecret_tmp
  notify: Remove externsecret temp dir

- name: Install External Secrets
  command: >
    helm upgrade --install
    external-secrets external-secrets/external-secrets
    --namespace external-secrets
    --create-namespace
    --version {{ external_secrets_version }}
  environment:
    KUBECONFIG: "{{ k3s_kubeconfig_path }}"
  register: manifest
  changed_when:
    - '"cannot re-use a name that is still in use" not in manifest.stderr'
  failed_when:
    - manifest.rc != 0
    - '"cannot re-use a name that is still in use" not in manifest.stderr'

- name: Create Secret Manifest File for AWS Access for ExternalSecrets ClusterSecretStore
  template: 
    src: "es-aws-access-secret.j2"
    dest: "{{ externsecret_tmp.path }}/es-aws-access-secret.yml"

- name: Create the ExternalSecrets ClusterSecretStore Manifest File
  template: 
    src: "es-cluster-secret-store.j2"
    dest: "{{ externsecret_tmp.path }}/es-cluster-secret-store.yml"
    
- name: Create Secret resource for AWS Access for External Secret Cluster Secret Store
  command: >
    kubectl apply -f {{ externsecret_tmp.path }}/es-aws-access-secret.yml
  environment:
    KUBECONFIG: "{{ k3s_kubeconfig_path }}"

- name: Create ClusterSecretStore resource for ExternalSecrets 
  command: >
    kubectl apply -f {{ externsecret_tmp.path }}/es-cluster-secret-store.yml
  environment:
    KUBECONFIG: "{{ k3s_kubeconfig_path }}"
