---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: sectigo-acme-clusterissuer
  namespace: cert-manager
spec:
  acme:
    disableAccountKeyGeneration: true
    email: devsupport@library.ucla.edu
    preferredChain: ""
    privateKeySecretRef:
      name: sectigo-acme-issueraccount-rsa-pem
    server: https://acme.sectigo.com/v2/InCommonRSAOV
    solvers:
    - http01:
        ingress:
          class: traefik
